FROM python:3.8

WORKDIR /app

COPY setup.sh .
RUN chmod +x setup.sh && ./setup.sh

COPY setup.py requirements.txt ./
RUN pip install . && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

RUN pip install notebook pandas matplotlib
COPY src/*.py /app/src/
COPY notebook/ /app/notebook/

EXPOSE 8501

CMD ["streamlit", "run", "app.py"]
