name: Python application test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover -s tests -k "not get_data_from_db"

      - name: Test database to CSV
        env:
          PG_HOST: localhost
          PG_USER: postgres
          PG_PASSWORD: postgres
          PG_PORT: 5432
          PG_DATABASE: telecom
          SQL_QUERY: "SELECT * FROM xdr_data"
          CSV_FILE: "xdr_data.csv"
        run: |
          python test_database_to_csv.py
